language: minimal
os: linux

services:
  - docker

git:
  depth: false  # Ensure latest tag is pulled

branches:
  only:
    - master

jobs:
  fast_finish: true

  include:
    - env:
      - CLUSTER_CONFIG=kerberos
    - env:
      - CLUSTER_CONFIG=simple

before_install:
  - ./continuous_integration/before_install.sh

install:
  - htcluster exec -- ./yarnspawner/continuous_integration/install.sh

script:
  - htcluster exec -- ./yarnspawner/continuous_integration/runtests.sh

notifications:
  email: false
