language: python
sudo: required
dist: trusty
os: linux
python:
  - "3.6"

services:
  - docker

git:
  depth: false  # Ensure latest tag is pulled

branches:
  only:
    - master

env:
  global:
    - secure: "ubuirmRkB/RANt2XdtvAlxjyYgfwy1i3wBnzq323ANqW3FJPeYogFa7iQaWDrjekg8azK9WXfHGF8yCNTkTHH1JlaXU9MiIveLUSVxR2PxjQRJyJ78pNOtNX5N+JQtA1pcgdfpkQ64nMSSSmgDlELBk5U9hOBD1y3or6yf38VtBp2HA2yt3ArfCTnv04ZaKkOVQA4JNCIjY8qVfym2KF6LvDQZGP9BoPllTY/c64w11Tt6rOCpcEm1inn94EBKsd3KjIeKP1nMG2150QqudiffRaPJ/Gtl0nbhFGITZtV1ylKc6NB/fkBQUIX+gXRXX9wKZWZ4a2yg7rcAnBiSpMEJoTxQCru5PbQHDSCmRupZb8YYIehuO6BsNOfZ7K+XMtcFHKaYk3CPGs01c7VRJ6fUcyd9k85ABu2Q7vCS5s5BT2XgX8hL+vLBMh3X/v2XFAUV2/z6INoapP3qRRog+DZgJ+w/bqI92pdiTGjqQPi6oROozv8xIyABR703KMKIpCWfBm4cQesQAqc4SZyBLvX0bwBX58l4xUaKeykDUHZ0zJte8aqT8cQNpXIs0FBbCc6XRNnM3wvfLc5LMHWOleUAV0w9EhDCyvMakGvPAcKBCq5pDxPsjSD/B57laGjUxMwSyIFly/Dz7j/pjnP6DITBRdTZz7RSGEdY9QGBhpVSo="

jobs:
  fast_finish: true

  include:
    - if: commit_message !~ skip-tests
      env:
      - CLUSTER_TYPE=kerberos
    - if: commit_message !~ skip-tests
      env:
      - CLUSTER_TYPE=base
    - sudo: false
      env:
        - DOCS=true

before_install:
  - |
    if [[ "$DOCS" != "true" ]]; then
        ./continuous_integration/before_install.sh
    fi

install:
  - |
    if [[ "$DOCS" != "true" ]]; then
        htcluster exec -- ./yarnspawner/continuous_integration/install.sh
    else
        pip install jupyterhub skein sphinx doctr
        pip install -e .
    fi

script:
  - |
    if [[ "$DOCS" != "true" ]]; then
        htcluster exec -- ./yarnspawner/continuous_integration/runtests.sh
    else
        ./continuous_integration/build_docs.sh
    fi

notifications:
  email: false
